### ISSUE TITLE
Need to document how to enable flowzone in non product-os repos

### ISSUE THREAD

**Issue by anujdeshpande** [product-os/flowzone#123]
Figuring that out for balena-io-hardware right now : https://jel.ly.fish/thread-5bd62f66-1041-447b-a27c-fda219f6db37
Will hopefully get some screenshots to add to the readme from this exercise

**Comment by klutchell** [comment]
Here's an example: https://github.com/balena-io/open-balena-registry-proxy/pull/48

**Comment by klutchell** [comment]
But I imaging the bit you are missing is all the secrets at the org level, which requires an owner and someone with access to all the secrets.

**Comment by anujdeshpande** [comment]
> But I imagine the bit you are missing is all the secrets at the org level, which requires an owner and someone with access to all the secrets.

@klutchell would I need "all" the secrets? I am not going to be using any of these -

```
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      DOCKERHUB_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_REGISTRY_PASS }}
      BALENA_API_KEY: ${{ secrets.BALENA_API_KEY }}
```

I think I'd only need
```
      FLOWZONE_TOKEN: ${{ secrets.FLOWZONE_TOKEN }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
```

which I will ask the ops team to set for my org

**Comment by klutchell** [comment]
Correct, you only need the latter 3. I have the values you need, but I'm not an owner of that org to set secrets.

We have already added a GPG key to the balena-ci GH user, you just need the secrets created.

**Comment by anujdeshpande** [comment]
@klutchell can you share those secrets with @LPapapo please?
He's helping me out with this [here](https://jel.ly.fish/thread-5bd62f66-1041-447b-a27c-fda219f6db37)

**Comment by ab77** [comment]
operational, resolved.
