### ISSUE TITLE
Versioned source action should fail when versionist fails

### ISSUE THREAD

**Issue by anujdeshpande** [product-os/flowzone#126]
I got the following logs [here](https://github.com/balena-io-hardware/hardware-process-test/runs/8019427840?check_suite_focus=true) - but the action passed. I think if versionist fails, the check should fail 

```
Unhandled rejection Error: Command failed: versionist --config=versionist.tmp.cjs 
No commits were annotated with a change type since version 0.1.0

    at ChildProcess.exithandler (node:child_process:400:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

**Comment by klutchell** [comment]
I'm not sure I agree, I think there is a use case to merge commits with no change-type. Up for discussion though.

**Comment by anujdeshpande** [comment]
@klutchell would we check for a `change-type` at the PR level in that case? So it's okay if a single commit doesn't have the change-type - but the PR as a whole should have atleast 1 change-type. 

Otherwise we'd have PRs that merge without updating the version of master - which is a problem as there won't be any releases for the latest HEAD of master

**Comment by anujdeshpande** [comment]
@klutchell This also breaks how we've done things with versionbot. So here we are also changing a default behavior that folks are probably used to.

I think it's not a good idea to have un-tagged changes in master, because when I say I am using `v2.3.4` of something you'll know exactly what I mean. If we have commits on top of `v2.3.4` it can be confusing. Someone might come to the repo and browse the source code - but they won't be looking at the release source code.

A project that I am working on would get quite confusing as the repo has only markdown files and nothing else. So folks normally just browse github when reading the docs.

I think if we are moving away from how versionbot did things we should atleast expose a flag which allows folks to do things the old way. What do you think? 
Happy to create an arch call topic if this requires one as well
