### ISSUE TITLE
Pull secrets from Vault

### ISSUE THREAD

**Issue by 20k-ultra** [product-os/flowzone#134]
Flowzone is configured to expect [these](https://github.com/product-os/flowzone/blob/master/.github/workflows/flowzone.yml#L9-L38) secrets. This requires setting secrets at the repo or org (preferred) level.

Setting the secrets at the org level is the preferred (I'd argue only acceptable way) because it makes rotating tokens much easier. However, this is at the risk of now someone needing to access the token and add them to orgs. With 1 org it's ok but what if you have 10 orgs for a company ? 

An alternative is to use an action like https://github.com/hashicorp/vault-action which lets you pull secrets from the vault. This makes rotating tokens simple since they are in 1 place, controlled by you.

**Comment by 20k-ultra** [comment]
One issue with pulling secrets from the Vault means that people using this action need a Vault.

The solution is to make the action have a step which adds secrets as an output like: `steps.secrets.outputs.npmToken`. This provides a generic interface for the workflow to get secrets regardless of where it's from.

The secret step will check if the required `vault_` secrets are set and pull values and set them as outputs. Otherwise, just set the secrets to the output.

This interface allows for some other controls to be added regarding secrets if you wanted. I'm not sure what but off the top of my head maybe you can do some analytics to phone home so you can see which repo is using your secrets the most or something so that if you do need to change/revoke the secrets you'll know which projects break.

**Comment by 20k-ultra** [comment]
@klutchell how cool is the secrets idea^ I didn't realize it until now but having secret usage analytics is super cool! I imagine hashicorp vault might already do something like that but there are many more possibilities

**Comment by klutchell** [comment]
Looks awesome dude!

**Comment by ab77** [comment]
I understood our self-hosted Vault will die with resinCI.

Do we really want to introduce a hosted Vault when we've just gone with BitWarden for secrets/UI?

Is there an action that will interface with BitWarden and if so, that would be preferable to another secrets manager.

And anyway, what's wrong with just plain GH secrets?

We can even have an action that rotates them on a regular basis.
