### ISSUE TITLE
Extend branch protection rules to amend vs replace

### ISSUE THREAD

**Issue by klutchell** [product-os/flowzone#141]
The current branch protection rules job will apply some hardcoded values for branch protection.

https://github.com/product-os/flowzone/blob/a4601e64e47fe1684828cb1848cbf7f36c3744a9/.github/workflows/flowzone.yml#L354-L390

However, we should allow custom required checks, reviewers, etc. This could best be solved by getting the current rules from the GitHub API, amending them, and putting them back to the GH endpoint.

1. GET existing protections from GitHub API
2. Convert to [JSON object](https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson)
3. Remove ResinCI checks
4. Add Flowzone checks
5. Leave other checks alone
6. Update required reviewers based on input
7. Convert back to [JSON string](https://docs.github.com/en/actions/learn-github-actions/expressions#tojson)
7. PUT back to GitHub API

**Comment by fisehara** [comment]
@klutchell can you please add some details about what:
1. Remove ResinCI checks are

**Comment by klutchell** [comment]
@fisehara 

1. The current resinCI checks can be found on any balena repo currently implementing resinCI. You can test this by removing `.resinci.yml` in this PR which will cause resinCI to start running on this PR again. Then you can see what tests are run, and these are the tests we would want to REMOVE from branch protection rules for repos adopting Flowzone.

2. The Flowzone checks we want to add are currently hardcoded. Ideally we could start producing these dynamically, but for now just the ability to remove any `resinCI / * ` and `Flowzone / *` checks and replace them with the current Flowzone checks would be enough to ensure that other unrelated branch rules are not lost. For example, if a branch rule depends on a Jenkins job we don't want to remove it. Hence the request to PATCH the branch rules vs POST.

We can get a meet today if that would help! LMK!
