### ISSUE TITLE
Generating CHANGELOG.yml fails when no versioned PRs have merged

### ISSUE THREAD

**Issue by mehalter** [product-os/flowzone#172]
I am setting up a new repository (very similar to https://github.com/balenaltd/handbook) It has never been versioned before and this is the first PR which we are hoping jump starts the versioning. It looks like flowzone is failing to generate the changelog probably due to the fact that it has never been "released" or versioned prior to the pull request

https://github.com/balenaltd/security/pull/1

The relevant logs of the error can be found here: https://github.com/balenaltd/security/runs/8142755809?check_suite_focus=true

**Comment by klutchell** [comment]
```
+ ./generate-changelog.sh .
Generating CHANGELOG.yml for `balenaltd/security`
Generating CHANGELOG.yml...
mv: cannot stat '/tmp/tmp.vD3pNx9o6K/v*.yml': No such file or directory
```
This script doesn't handle situations where the repo has never had a versioned PR merged.
https://github.com/product-os/versionist/blob/master/scripts/generate-changelog.sh

Versionist needs a lot of work, including fixing this script, but for now we can have Flowzone ignore this failure and get the new version via some fallback method.
