### ISSUE TITLE
Flowzone commit scripts

### ISSUE THREAD

**Issue by 20k-ultra** [product-os/flowzone#177]
Flowzone committed a few scripts that are not relevant to my repository 

See: https://github.com/balenaltd/security/commit/9e419fa228592c147700cb78c52367da7f03bbae#diff-c156061b47b0361d24e96c61eafdd435086fa7b8b0c5345c16460c846418f99a

**Comment by klutchell** [comment]
Ah, that's a new edge case introduced by being the first versioned commit on the repo. I'll fix this ASAP since it's a one line change.

**Comment by klutchell** [comment]
Some kind of automated testing would have caught this :eyes:
