### ISSUE TITLE
Some method for specifying npm install system dependencies

### ISSUE THREAD

**Issue by Page-** [product-os/flowzone#201]
eg using a native module which requires dbus requires that dbus is installed in the environment in order for `npm ci` to work

**Comment by ab77** [comment]
https://github.com/product-os/flowzone/pull/203

... look for `package.txt` and pipe it to `apt-get install -y`

**Comment by ab77** [comment]
@pipex @cywang117 @Page- do we still need this or is [this](https://github.com/balena-os/balena-supervisor/pull/2010/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R28) adequate?

**Comment by cywang117** [comment]
@ab77 The preinstall script for the Supervisor specifically works. The case may be different for repos that use Flowzone in general though. @klutchell has a vision for Flowzone last time I opened an issue here so I'm curious what he thinks.

**Comment by klutchell** [comment]
I like @ab77's solution in #203 but it's even better if we don't need it. As far as I can tell, npm is the only project type that might require a pre-install of some kind and it already supports it natively via package.json?

I would think that docker(-compose) and balena packages would never have local dependencies. So maybe we shelf the package.txt solution until we find a need for it?

**Comment by ab77** [comment]
> npm is the only project type

If we support Python, there may be system dependencies as well prior to running `pip install -r ...`

**Comment by Page-** [comment]
This can be handled by #216 using a `flowzone-preinstall` script in package.json

**Comment by Page-** [comment]
For reference a standard `preinstall` script does not work on npm 7+ because the preinstall script happens after dependencies are installed, which kind of scuppers things if the dependency is what requires the native module
