### ISSUE TITLE
Called workflows cannot be queued onto self-hosted runners across organisations/enterprises.

### ISSUE THREAD

**Issue by ab77** [product-os/flowzone#225]
See, https://github.com/balena-io/environment-staging/actions/runs/3109617436 and https://github.com/balena-io/environment-staging/pull/717

A workflow called in balena-io (from product-os) appears not to be schedule-able on self-hosted runners. Could be a GH limitation.

**Comment by ab77** [comment]
For a laugh, logged a ticket under my personal account: https://support.github.com/ticket/personal/0/1806898

Let's see what they say...

**Comment by ab77** [comment]
I've confirmed with GH support, a workflow called in balena-io (from product-os) and scheduled on self-hosted runners, requires both orgs to be part of an enterprise. So we'll need to upgrade our GH plan(s), or make everything public. cc @klutchell @Page-

**Comment by klutchell** [comment]
I believe we are already in the process of upgrading our plan.

**Comment by ab77** [comment]
> I believe we are already in the process of upgrading our plan.

@apostolism @LPapapo can you folks confirm or deny this?

**Comment by codewithcheese** [comment]
Upgraded to enterprise.
