### ISSUE TITLE
COMPOSE_VARS secret will leak base64 encoded if copied to stdout|err|terminal

### ISSUE THREAD

**Issue by ab77** [product-os/flowzone#236]
Since the `COMPOSE_VARS` is base64 encoded before being stored as a secret, only the base64 encoded value will be protected from leakage by GH actions runners.

Once the value is unwrapped, GH runners will no longer match the secret hash and if the value makes it to some output, the secret values will leak into the runner logs.

**Comment by klutchell** [comment]
Fixed by https://github.com/product-os/flowzone/pull/336

**Comment by klutchell** [comment]
Related to https://github.com/product-os/flowzone/issues/332

For external contributions this secret is not allowed and will exit the workflow. However there is still the possibility for internal contributors to accidentally leak this value and as such it should be deprecated.

**Comment by ab77** [comment]
Fixed: https://github.com/product-os/flowzone/blob/master/flowzone.yml#L1299-L1304
