### ISSUE TITLE
Publish images to GitHub Container Registry (ghcr.io)

### ISSUE THREAD

**Issue by ab77** [product-os/flowzone#255]
We already have a proto-action here: https://github.com/balena-io/deploy-to-balena-action/blob/master/.github/workflows/deploy_release.yml and it would be good to lose it and make this functionality available as part of Flowzone core.

**Comment by klutchell** [comment]
This is already in Flowzone core, just provide a ghcr.io URL in the `docker_images` input.
https://github.com/product-os/flowzone/blob/da1a44d07976e0c30f3bb31498f94ee7e8dcd19f/.github/workflows/tests.yml#L18-L19
