### ISSUE TITLE
Updating a PR with a new commit does not build a new draft release

### ISSUE THREAD

**Issue by builder555** [product-os/flowzone#328]
When a PR is updated with a new commit, FZ should build a new draft release, instead of reusing the previous one.

[Here is an example](https://github.com/balena-io-hardware/EtcherPro-Fleet/actions/runs/3445112554/jobs/5748484478#step:5:40) of a workflow that should have built a new release. 

Relevant log:
```
For further help or support, visit:
https://www.balena.io/docs/reference/balena-cli/#support-faq-and-troubleshooting

git version 2.30.2
Initializing SDK for [https://api.balena-cloud.com)](https://api.balena-cloud.com%29/)
Checking if a release has already been built.
Found existing release.
```

**Comment by ab77** [comment]
@builder555 This may have been fixed, can you retry please?
