### ISSUE TITLE
When a repo pushes to a Block on Hub it uses docker-compose.yml by mistake

### ISSUE THREAD

**Issue by maggie0002** [product-os/flowzone#420]
When a repo contains a Dockerfile and docker-compose.yml file and pushes to the Hub as a block, Flowzone/the builders will use the docker-compose.yml file by default. This results in an error where the pull command for the container will fail (see the linked issue below). To resolve this, I had to rename docker-compose.yml to docker-compose-example.yml to avoid Flowzone/the builders building from the wrong file. 

Potential fixes could be for Flowzone to read the balena.yml file `type` field and check to see if it is configured as a block or an app. Alternatively, and perhaps ideally on the builder end which receives both files it identifies where it is pushing the code (to a block or an App) and defaults to Dockerfile instead of docker-compose.yml. 

cc. @klutchell as potentially linked to Flowzone and the builders and may have some thoughts. 

https://jel.ly.fish/support-thread-discourse-366366

**Comment by klutchell** [comment]
@maggie0002 blocks can be deployed with docker-compose files, that is the normal practice. The only limitation is that the deployment must contain only one service (so their compose file must only have one service).

Also, the behaviour of preferring compose files applies to the `balena push` command and has nothing to do with Flowzone or the deploy-to-balena action.
