### ISSUE TITLE
Premature merging when branch protection job skipped

### ISSUE THREAD

**Issue by ab77** [product-os/flowzone#549]
When branch protection is skipped on PR target and before the job is registered on PR, pull requests can be merged without completing the workflows

<img width="878" alt="image" src="https://user-images.githubusercontent.com/2033996/224889997-9669a8bd-c503-4971-9ff4-b9fc79610a18.png">

**Comment by klutchell** [comment]
Interesting that they are both marked as required, I see the same thing on internal repos with PRT enabled.
![image](https://user-images.githubusercontent.com/20458272/225093962-99051da4-ab3a-46fc-b4bc-710645d646db.png)

**Comment by klutchell** [comment]
This wouldn't be an issue if required checks resolved only with 'success' and not 'skipped'.

**Comment by klutchell** [comment]
This can be solved by adding this condition to every calling workflow, but it's ugly and will require updating all the calling repos. This check already exists in Flowzone core but obviously the jobs are still populated as skipped.

https://github.com/product-os/flowzone/blob/cf400dc26ef28b7cb7b8ccc5552d04fa9f2dc79e/.github/workflows/tests.yml#L17-L24

**Comment by klutchell** [comment]
This is the main issue: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

We are not skipping the workflow in the case of `pull_request_target`, we are skipping all jobs in the workflow. The difference is skipped jobs are considered success.

The above snippet in every workflow file would workaround this.

**Comment by ab77** [comment]
> The above snippet in every workflow file would workaround this.

The more I look at this, the more I like it. It also reduces noise.

**Comment by klutchell** [comment]
> Updating upstream repos can always be automated

I actually have an idea for this, and now seems like a good time to try it out.

**Comment by klutchell** [comment]
balena-os device repositories have been patched: https://github.com/product-os/flowzone/actions/runs/4440157423

**Comment by klutchell** [comment]
There is another condition where this occurs: https://github.com/balena-os/renovate-config/issues/27

Will look into workarounds since Flowzone already gets a list of required jobs from the repo config. We could potentially use that to block steps until required jobs are registered.
