### ISSUE TITLE
Tag Command doesn't work 

### ISSUE THREAD

**Issue by vipulgupta2048** [product-os/flowzone#713]
https://github.com/product-os/flowzone/blob/fe7b608c37e49f3d1ee72344f0fead3157ac2961/flowzone.yml#L116

This command turns up empty when I was in process of stealing it for another job. Using `git describe` to extract the tag seems to be working. Reporting here for y'all to double check. 

```bash
~/work/leviathan-worker$ git tag --points-at HEAD
~/work/leviathan-worker$ git describe --tags --always --dirty
v2.4.1-184-gb015d6d9
~/work/leviathan-worker$ npx -q -y -- semver -c -l "$(git describe --tags --always --dirty)"
2.4.1
```

Might remove `--dirty` flag to get the desired outcome

Not quite sure why it isn't working for. It is not the wrong command as also stated here: https://stackoverflow.com/questions/56788186/git-detect-that-local-head-is-pointing-to-a-git-tag

**Comment by klutchell** [comment]
@vipulgupta2048 `git tag --points-at HEAD` will only return the tags that are on the current HEAD commit. So if the current commit is not tagged directly it should return nothing.

This line is only used by Flowzone if versioning is disabled, and instead done manually by tagging commits, in which case the above would return a tag.
