### ISSUE TITLE
Consider using only docker-compose.test.yml for docker tests

### ISSUE THREAD

**Issue by klutchell** [product-os/flowzone#94]
Currently we require both `docker-compose.yml` and `docker-compose.test.yml` for docker tests and we apply them both with docker-compose up.

https://github.com/product-os/flowzone/blob/868d5863697f2168b094d41555bcf6c2e2f60ea0/.github/workflows/flowzone.yml#L727

However, the [Docker Hub tests](https://docs.docker.com/docker-hub/builds/automated-testing/) only use `docker-compose.test.yml` and it might make things simpler to only require the one file rather than merging them.

We should find out why resinCI required both files and the reasoning behind it.

**Comment by fisehara** [comment]
At the time when i utilised docker-compose testing in pinejs there was no knowledge available why the redundant docker-compose file is in place.

**Comment by fisehara** [comment]
Added a switch to check if both docker-compose files exists. 
If only a docker-compose.test.yml exists, the composition is run from this file only
